### ISSUE TITLE
训练准确率

### ISSUE THREAD

**Issue by yw1991** [yeyupiaoling/LearnPaddle2#1]
![image](https://user-images.githubusercontent.com/21213333/61200148-17fa2f00-a713-11e9-9918-346288f74530.png)
这个准确率有点低了  loss一直不下降

**Comment by yeyupiaoling** [comment]
@yw1991 你说的是哪一个例子？

**Comment by yw1991** [comment]
> @yw1991 你说的是哪一个例子？

对不起，之前没有说清楚，就是note12，利用paddle做文本分类，我大概下载了20万条的数据，进行训练，但是这个结果就是和上图显示那样。是什么原因？

**Comment by yeyupiaoling** [comment]
@yw1991 是不是你数据集的问题？你有没有试过我的数据集和模型？应该没有问题的、

**Comment by yw1991** [comment]
> 应该没有问题的、

我还没试过你的数据集，有时间的话试试，不过我没有看到你的数据集

**Comment by yw1991** [comment]
您好，你用过paddle做过短文本相似度计算吗？就是paddlenlp底下的similarity_net?我实现了一下，但是有点疑问？想和您沟通一下？@yeyupiaoling

**Comment by yeyupiaoling** [comment]
@yw1991 你好，我对自然语言理解不是太了解，你是有什么问题吗？

**Comment by yw1991** [comment]
好吧，我训练完了感觉百度官网上短文本相似度案例和这个paddlenlp下这个有点不一样，就是对他这个结果有点疑问。您如果没有做过的话就不知道和你怎么描述了；谢谢，要是方便的话能加个好友有问题可以好好聊聊。


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: 夜雨飘零 <notifications@github.com>
发送时间: 2019年7月15日 22:16
收件人: yeyupiaoling/LearnPaddle2 <LearnPaddle2@noreply.github.com>
抄送: yw1991 <861484926@qq.com>, Mention <mention@noreply.github.com>
主题: 回复：[yeyupiaoling/LearnPaddle2] 训练准确率 (#1)




@yw1991 你说的是哪一个例子？
