### ISSUE TITLE
ask for your help!

### ISSUE THREAD

**Issue by hippo-zhou** [yeyupiaoling/LearnPaddle2#2]
when runing train.py, i find that there is no "cublas_90.dll".

**Comment by yeyupiaoling** [comment]
What is the PaddlePaddle version you use？@hippo-zhou 
You try reloading it.

**Comment by hippo-zhou** [comment]
谢谢了，这个问题已经解决了，出现了一个新的问题，我想把模型部署到移动端，我的操作系统是windows，按照你的步骤我使用docker，编译了paddle-mobile,运行镜像进入容器执行cmake 命令 出现了错误，详情如图。考虑到你所使用的是乌班图系统，是否运行镜像进入容器的命令需要修改？


 



------------------ 原始邮件 ------------------
发件人: "夜雨飘零"<notifications@github.com>; 
发送时间: 2019年7月29日(星期一) 上午8:49
收件人: "yeyupiaoling/LearnPaddle2"<LearnPaddle2@noreply.github.com>; 
抄送: "ing"<1157046524@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [yeyupiaoling/LearnPaddle2] ask for your help! (#2)




What is the PaddlePaddle version you use？@hippo-zhou
 You try reloading it.
